---

- hosts: all
  become: true
  pre_tasks: 

  - name: install updates (Rocky Linux)
    tags: always
    dnf:
      update_only: yes
      update_cache: yes
    when: ansible_distribution == "Rocky Linux"

  - name: install updates (Ubuntu)
    tags: always
    apt:
      upgrade: dist
      update_cache: yes
    when: ansible_distribution == "Ubuntu"

- hosts: web_servers
  become: true
  tasks: 

  - name: install apache and php for Ubuntu Servers
    tags: apache,apache2,ubuntu
    apt:
      name:
        - apache2
        - libapache2-mod-php
      state: latest
      
    when: ansible_distribution == "Ubuntu"

  - name: install apache and php for Rock Linux servers
    tags: apache,rockylinux,httpd
    dnf:
      name:
        - httpd
        - php
      state: latest
      update_cache: yes
    when: ansible_distribution == "Rocky Linux"

- hosts: db_servers
  become: true
  tasks: 

  - name: install mariadb package (Rocky Linux)
    tags: rockylinux,db,mariadb
    dnf:
      name: mariadb
      state: latest
    when: ansible_distribution == "Rocky Linux"

  - name: install mariadb package (Ubuntu)
    tags: db,mariadb,ubuntu
    apt:
      name: mariadb-server
      state: latest
    when: ansible_distribution == "Ubuntu"
      
- hosts: file_servers
  become: true
  tasks:

  - name: install samba package
    tags: samba
    package:
      name: samba
      state: latest
