- name: Add SSH key for Jeanette
  authorized_key:
    user: jeanette
    key: "ssh-ed25519 AAAAC3NzaC1lZDI1NTE5AAAAIFOG3Msi4lPvBsNsC6MOrU9NfbAXKaa8xFj5/8btfuio ansible" 

- name: generate sshd_config file from template
  tags: ssh
  template:
    src: "{{ ssh_template_file }}"
    dest: /etc/ssh/sshd_config
    owner: root
    group: root
    mode: 0644
  notify: restart_sshd
