- name: Install mariadb server package (Rocky)
  tags: rocky,db,mariadb
  dnf:
    name: mariadb
    state: latest
  when: ansible_distribution == "Rocky"

- name: Install mariadb server package (Ubuntu)
  tags: db,mariadb,ubuntu
  apt: 
    name: mariadb-server
    state: latest
  when: ansible_distribution == "Ubuntu"
